on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string
      esphome-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build ESPHome firmware
        uses: esphome/build-action@v7
        with:
          yaml-file: ${{ inputs.file }}